name: 'test'

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm install
      - run: npm test
  # Test run action in dry mode.
  action:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ./
        with:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          # Manually trigger a dry run to see if action would work.
          DRY_RUN: true
          MANUAL_TRIGGER: regular
          FAIL_ON_SKIP: false
